### ISSUE TITLE
Upload to Unity Asset Store

### ISSUE THREAD

**Issue by knsh14** [KLab/klab-messagebuses-unity#1]
I know this library is great.
but In ordinary workflow, we get any models, textures and scripts from [Unity Asset Store]( https://assetstore.unity.com ).

so I want you to upload this library to Asset Store and make it easy to import to project.

**Comment by knsh14** [comment]
FYI
https://unity3d.com/jp/asset-store/sell-assets
https://docs.unity3d.com/Manual/AssetStorePublishingGuide.html

**Comment by g-a-n-d-i** [comment]
@knsh14 cc @nyamadan

> I know this library is great.

Thanks for the heads up!

> In ordinary workflow, we get any models, textures and scripts from Unity Asset Store.
> 
> so I want you to upload this library to Asset Store and make it easy to import to project.

I highly recommend using Unity 2018's package manager to get the library into your project. That way, the library files don't end up under the `./Asset` directory of your project and the library itself is shown under `Packages` in the project window within Unity. As the library comes with a `package.json`, all you have to do is add one line to the `manifest.json` in your project. Here's a link to a gist that shows you how to do it:

https://gist.github.com/LotteMakesStuff/6e02e0ea303030517a071a1c81eb016e#file-2-example-manifest-json

If you're on Unity 2018.3, importing the package becomes even simpler: 

https://twitter.com/cirocontns/status/1039060910223118336

That, of course, requires your project to use Unity 2018...
... are you using Unity 2017?

**Comment by knsh14** [comment]
I use Unity 2018.2. I succeed to import MBus by following steps.

1. clone into local dir.
2. Add `"com.klab.messagebuses": "PATH/TO/klab-messagebuses-unity"` into manifest.json.

thank you for information!

**Comment by g-a-n-d-i** [comment]
Just a quick update: Unity know also allows you to load local packages from within the Package Manager UI, so let me close this issue as solved, right?

https://docs.unity3d.com/Packages/com.unity.package-manager-ui@2.1/manual/index.html#extpkg
